openapi: 3.0.3
info:
    title: Flight Service
    description: Service for creating, deleteing, updating and searching for available flights
    termsOfService: Terms of use
    contact:
        name: API Support
        url: https://example.com/api-support
        email: support@example.com
    version: "0.1"
servers:
    - url: https://{version}.goa.design/calc
      description: calcsvr hosts the Calculator Service.
      variables:
        version:
            default: v1
    - url: http://localhost:80/calc
      description: calcsvr hosts the Calculator Service.
paths:
    /:
        get:
            tags:
                - booking
            summary: book booking
            description: Book a flight using IATA NDC standard
            operationId: booking#book
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SearchRequestBody'
                        example:
                            departure_date: Est qui ratione dolor vel debitis.
                            destination: 23m
                            one_way: false
                            origin: r92
                            return_date: Officia dolorem ut maiores optio aliquid et.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlightBooking'
                            example:
                                departure_date: Ab officia quas aut sint.
                                destination: Aut sed ut.
                                id: 4599875665897917257
                                origin: Inventore excepturi sit vel id placeat ex.
                                return_date: Soluta ut.
                                status: Ut est est.
components:
    schemas:
        FlightBooking:
            type: object
            properties:
                departure_date:
                    type: string
                    description: Departure Date (YYYY-MM-DD)
                    example: Aut ut dolorem.
                destination:
                    type: string
                    description: Destination Airport Code
                    example: Quia suscipit porro quo in sapiente.
                id:
                    type: integer
                    description: Unique Flight Booking Identifier
                    example: 5646177957691260419
                    format: int64
                origin:
                    type: string
                    description: Origin Airport Code
                    example: Quisquam velit officiis est sit.
                return_date:
                    type: string
                    description: Return Date (YYYY-MM-DD)
                    example: Neque voluptate itaque perferendis nihil.
                status:
                    type: string
                    description: Status of the booking (pending, confirmed, cancelled)
                    example: Quasi perferendis vitae accusamus.
            example:
                departure_date: Et quas optio impedit inventore.
                destination: Molestias et maxime.
                id: 5571308249449550652
                origin: Consequatur ut in expedita alias ex.
                return_date: Et et iure.
                status: Ex aspernatur deleniti cupiditate non iusto incidunt.
            required:
                - id
                - origin
                - destination
                - departure_date
                - return_date
                - status
        Flightresult:
            type: object
            properties:
                departure_date:
                    type: string
                    description: Departure Date (YYYY-MM-DD)
                    example: Quas cupiditate dolor aspernatur.
                destination:
                    type: string
                    description: Destination Airport Code
                    example: Provident sit sunt ut eos sapiente.
                id:
                    type: integer
                    description: Unique Flight Booking Identifier
                    example: 8325523797987193740
                    format: int64
                origin:
                    type: string
                    description: Origin Airport Code
                    example: Qui non laboriosam quasi vitae magnam est.
                return_date:
                    type: string
                    description: Return Date (YYYY-MM-DD)
                    example: Temporibus sed.
                status:
                    type: string
                    description: Status of the booking (pending, confirmed, cancelled)
                    example: Asperiores voluptates quis.
            example:
                departure_date: Molestiae sequi ea.
                destination: Modi velit quod quo quisquam saepe consequatur.
                id: 1808247823571320946
                origin: Rem minima cupiditate vel.
                return_date: Et sequi velit.
                status: Autem quidem beatae voluptas dolores.
            required:
                - id
                - origin
                - destination
                - departure_date
                - return_date
                - status
        FlightresultCollection:
            type: array
            items:
                $ref: '#/components/schemas/Flightresult'
            example:
                - departure_date: Non sed assumenda cumque autem delectus odit.
                  destination: Rem quaerat recusandae.
                  id: 8841375107698388839
                  origin: Ut consequatur accusantium.
                  return_date: Tempora sed aut omnis.
                  status: Ipsam corrupti illo.
                - departure_date: Non sed assumenda cumque autem delectus odit.
                  destination: Rem quaerat recusandae.
                  id: 8841375107698388839
                  origin: Ut consequatur accusantium.
                  return_date: Tempora sed aut omnis.
                  status: Ipsam corrupti illo.
                - departure_date: Non sed assumenda cumque autem delectus odit.
                  destination: Rem quaerat recusandae.
                  id: 8841375107698388839
                  origin: Ut consequatur accusantium.
                  return_date: Tempora sed aut omnis.
                  status: Ipsam corrupti illo.
        SearchRequestBody:
            type: object
            properties:
                departure_date:
                    type: string
                    description: Departure date and time
                    example: Est corporis harum reiciendis.
                destination:
                    type: string
                    description: Destination airport code
                    example: 2np
                    minLength: 3
                    maxLength: 3
                one_way:
                    type: boolean
                    description: True for one-way searches, false for round trip searches
                    example: false
                origin:
                    type: string
                    description: Origin airport code
                    example: akf
                    minLength: 3
                    maxLength: 3
                return_date:
                    type: string
                    description: Return date and time (for round trip searches)
                    example: Explicabo ducimus corporis quos.
            example:
                departure_date: Impedit placeat in voluptatibus dolor suscipit.
                destination: w5i
                one_way: false
                origin: fxd
                return_date: Delectus aliquid deserunt cumque dolor.
            required:
                - origin
                - destination
                - departure_date
                - one_way
tags:
    - name: flight
    - name: booking
